server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myweb_database?userunicode=true&characterSet=utf-8
    username: root
    password: 2312011989
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #关闭模板引擎的缓存
  thymeleaf:
    cache: false
logging:
  level:
    root: info
    com.volerde: debug
comment.avatar: /images/avatar.jpg